SELECT * FROM MAX75MV.WORKORDER WHERE
    ISTASK = 0 and
    SITEID = 'AN-CT' AND
    STATUS <> 'CAN'  AND

    CHANGEDATE BETWEEN TO_DATE('2025-11-08', 'YYYY-MM-DD') AND
                       TO_DATE('2025-11-10', 'YYYY-MM-DD')
;
